In [1]:
import pandas as pd #import

In [2]:
x = pd.read_csv('entradas_breast.csv') #le o csv

In [3]:
x #print do csv

,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave_points_mean,symmetry_mean,fractal_dimension_mean,...,radius_worst,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave_points_worst,symmetry_worst,fractal_dimension_worst
0,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.30010,0.14710,0.2419,0.07871,...,25.38,17.33,184.60,2019.0,0.16220,0.66560,0.7119,0.2654,0.4601,0.11890
1,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.08690,0.07017,0.1812,0.05667,...,24.99,23.41,158.80,1956.0,0.12380,0.18660,0.2416,186.0000,275.0000,0.08902
2,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.19740,0.12790,0.2069,0.05999,...,23.57,25.53,152.50,1709.0,0.14440,0.42450,0.4504,243.0000,0.3613,0.08758
3,11.42,20.38,77.58,386.1,0.14250,0.28390,0.24140,0.10520,0.2597,0.09744,...,14.91,26.50,98.87,567.7,0.20980,0.86630,0.6869,0.2575,0.6638,173.00000
4,20.29,14.34,135.10,1297.0,0.10030,0.13280,198.00000,0.10430,0.1809,0.05883,...,22.54,16.67,152.20,1575.0,0.13740,205.00000,0.4000,0.1625,0.2364,0.07678
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
564,21.56,22.39,142.00,1479.0,111.00000,0.11590,0.24390,0.13890,0.1726,0.05623,...,25.45,26.40,166.10,2027.0,141.00000,0.21130,0.4107,0.2216,206.0000,0.07115
565,20.13,28.25,131.20,1261.0,0.09780,0.10340,144.00000,0.09791,0.1752,0.05533,...,23.69,38.25,155.00,1731.0,0.11660,0.19220,0.3215,0.1628,0.2572,0.06637
566,16.60,28.08,108.30,858.1,0.08455,0.10230,0.09251,0.05302,159.0000,0.05648,...,18.98,34.12,126.70,1124.0,0.11390,0.30940,0.3403,0.1418,0.2218,0.07820
567,20.60,29.33,140.10,1265.0,0.11780,277.00000,0.35140,152.00000,0.2397,0.07016,...,25.74,39.42,184.60,1821.0,165.00000,0.86810,0.9387,265.0000,0.4087,124.00000
568,7.76,24.54,47.92,181.0,0.05263,0.04362,0.00000,0.00000,0.1587,0.05884,...,9456.00,30.37,59.16,268.6,0.08996,0.06444,0.0000,0.0000,0.2871,0.07039

In [4]:
y = pd.read_csv('saidas_breast.csv')
y #le e printa

     0
0    0
1    0
2    0
3    0
4    0
..  ..
564  0
565  0
566  0
567  0
568  1

[569 rows x 1 columns]

In [5]:
import sklearn
from sklearn.model_selection import train_test_split #imports

In [6]:
X_train, X_test, Y_train, Y_test = train_test_split(x, y, test_size = 0.25) #divide os dados em treino e teste

In [7]:
X_train.shape #o tamanho do X de treino

(426, 30)

In [8]:
X_test.shape #tamanho do X de teste

(143, 30)

In [10]:
import tensorflow as tf
from tensorflow.keras.models import Sequential #imports

In [11]:
rede_neural = Sequential([
    tf.keras.layers.InputLayer(shape = (30,)),
    tf.keras.layers.Dense(units = 16, activation = 'relu', kernel_initializer = 'random_uniform'),
    tf.keras.layers.Dense(units = 1, activation = 'sigmoid')
]) #criando a rede neural em si com os algoritimos e a camada oculta

I0000 00:00:1779547989.101266   28345 gpu_device.cc:2043] Created device /job:localhost/replica:0/task:0/device:GPU:0 with 4118 MB memory:  -> device: 0, name: NVIDIA GeForce RTX 3050 6GB Laptop GPU, pci bus id: 0000:01:00.0, compute capability: 8.6

In [12]:
rede_neural.summary() #ver como a rede neural esta criada

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense (Dense)                   │ (None, 16)             │           496 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 1)              │            17 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 513 (2.00 KB)

 Trainable params: 513 (2.00 KB)

 Non-trainable params: 0 (0.00 B)

In [14]:
rede_neural.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['binary_accuracy']) #compilando a rede

In [16]:
rede_neural.fit(X_train, Y_train, batch_size = 10, epochs = 100) #treinando ela

Epoch 1/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - binary_accuracy: 0.6901 - loss: 1.7162
Epoch 2/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - binary_accuracy: 0.7700 - loss: 1.0201
Epoch 3/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - binary_accuracy: 0.7887 - loss: 0.9758
Epoch 4/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - binary_accuracy: 0.8545 - loss: 0.5903
Epoch 5/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - binary_accuracy: 0.7864 - loss: 0.8169
Epoch 6/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - binary_accuracy: 0.8568 - loss: 0.5780
Epoch 7/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - binary_accuracy: 0.8944 - loss: 0.4337
Epoch 8/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - binary_accuracy: 0.8169 - loss: 0.9320
Epoch 9/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - binary_accuracy: 0.8732 - loss: 0.4431
Epoch 10/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - binary_accuracy: 0.9014 - loss: 0.3152
Epoch 11/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - binary_accuracy: 0.8850 - loss: 0.4458
Epoch 12/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - binary_accuracy: 0.8897 - loss: 0.4321
Epoch 13/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - binary_accuracy: 0.8967 - loss: 0.3473
Epoch 14/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - binary_accuracy: 0.9131 - loss: 0.3940
Epoch 15/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - binary_accuracy: 0.8662 - loss: 0.4629
Epoch 16/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - binary_accuracy: 0.8451 - loss: 0.7236
Epoch 17/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - binary_accuracy: 0.8732 - loss: 0.5438
Epoch 18/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - binary_accuracy: 0.9249 - loss: 0.3147
Epoch 19/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - binary_accuracy: 0.9108 - loss: 0.3305
Epoch 20/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - binary_accuracy: 0.9131 - loss: 0.2646
Epoch 21/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - binary_accuracy: 0.8263 - loss: 0.7925
Epoch 22/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - binary_accuracy: 0.8850 - loss: 0.4638
Epoch 23/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - binary_accuracy: 0.8920 - loss: 0.4877
Epoch 24/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - binary_accuracy: 0.9202 - loss: 0.3637
Epoch 25/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - binary_accuracy: 0.9131 - loss: 0.3586
Epoch 26/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - binary_accuracy: 0.9038 - loss: 0.3126
Epoch 27/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - binary_accuracy: 0.9155 - loss: 0.2981
Epoch 28/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - binary_accuracy: 0.9085 - loss: 0.2423
Epoch 29/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - binary_accuracy: 0.9202 - loss: 0.2752
Epoch 30/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - binary_accuracy: 0.9225 - loss: 0.2731
Epoch 31/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - binary_accuracy: 0.9178 - loss: 0.3198
Epoch 32/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - binary_accuracy: 0.8662 - loss: 0.6041
Epoch 33/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - binary_accuracy: 0.8991 - loss: 0.4571
Epoch 34/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - binary_accuracy: 0.9038 - loss: 0.3455
Epoch 35/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - binary_accuracy: 0.9061 - loss: 0.3332
Epoch 36/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - binary_accuracy: 0.8873 - loss: 0.5041
Epoch 37/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - binary_accuracy: 0.8944 - loss: 0.4964
Epoch 38/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - binary_accuracy: 0.8779 - loss: 0.7008
Epoch 39/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - binary_accuracy: 0.8920 - loss: 0.5644
Epoch 40/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - binary_accuracy: 0.9085 - loss: 0.4853
Epoch 41/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - binary_accuracy: 0.8944 - loss: 0.4197
Epoch 42/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - binary_accuracy: 0.8991 - loss: 0.4751
Epoch 43/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - binary_accuracy: 0.8803 - loss: 0.3971
Epoch 44/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - binary_accuracy: 0.9202 - loss: 0.3400
Epoch 45/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - binary_accuracy: 0.9225 - loss: 0.3131
Epoch 46/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - binary_accuracy: 0.9038 - loss: 0.4333
Epoch 47/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - binary_accuracy: 0.9343 - loss: 0.2298
Epoch 48/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - binary_accuracy: 0.9225 - loss: 0.1992
Epoch 49/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - binary_accuracy: 0.9108 - loss: 0.3786
Epoch 50/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - binary_accuracy: 0.9061 - loss: 0.4646
Epoch 51/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - binary_accuracy: 0.8615 - loss: 0.6239
Epoch 52/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - binary_accuracy: 0.8991 - loss: 0.5755
Epoch 53/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - binary_accuracy: 0.9249 - loss: 0.3677
Epoch 54/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - binary_accuracy: 0.9319 - loss: 0.3155
Epoch 55/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - binary_accuracy: 0.9178 - loss: 0.3306
Epoch 56/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - binary_accuracy: 0.9319 - loss: 0.2720
Epoch 57/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - binary_accuracy: 0.9366 - loss: 0.2926
Epoch 58/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - binary_accuracy: 0.9343 - loss: 0.2037
Epoch 59/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - binary_accuracy: 0.8873 - loss: 0.4415
Epoch 60/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - binary_accuracy: 0.8803 - loss: 0.7129
Epoch 61/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - binary_accuracy: 0.9178 - loss: 0.2981
Epoch 62/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - binary_accuracy: 0.8756 - loss: 0.6679
Epoch 63/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - binary_accuracy: 0.9319 - loss: 0.3705
Epoch 64/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - binary_accuracy: 0.9272 - loss: 0.2692
Epoch 65/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - binary_accuracy: 0.9202 - loss: 0.3147
Epoch 66/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - binary_accuracy: 0.9460 - loss: 0.1916
Epoch 67/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - binary_accuracy: 0.9413 - loss: 0.2475
Epoch 68/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - binary_accuracy: 0.9155 - loss: 0.3886
Epoch 69/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - binary_accuracy: 0.9085 - loss: 0.4683
Epoch 70/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - binary_accuracy: 0.9085 - loss: 0.4603
Epoch 71/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - binary_accuracy: 0.9319 - loss: 0.3272
Epoch 72/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - binary_accuracy: 0.8545 - loss: 0.7658
Epoch 73/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - binary_accuracy: 0.8826 - loss: 0.7063
Epoch 74/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - binary_accuracy: 0.9014 - loss: 0.7011
Epoch 75/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - binary_accuracy: 0.8333 - loss: 1.6530
Epoch 76/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - binary_accuracy: 0.9319 - loss: 0.3848
Epoch 77/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - binary_accuracy: 0.9296 - loss: 0.3041
Epoch 78/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - binary_accuracy: 0.9202 - loss: 0.3280
Epoch 79/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - binary_accuracy: 0.9390 - loss: 0.2273
Epoch 80/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - binary_accuracy: 0.9413 - loss: 0.2849
Epoch 81/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - binary_accuracy: 0.9319 - loss: 0.3200
Epoch 82/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - binary_accuracy: 0.9413 - loss: 0.2209
Epoch 83/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - binary_accuracy: 0.9413 - loss: 0.2467
Epoch 84/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - binary_accuracy: 0.9531 - loss: 0.2632
Epoch 85/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - binary_accuracy: 0.9460 - loss: 0.2538
Epoch 86/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - binary_accuracy: 0.9225 - loss: 0.2865
Epoch 87/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - binary_accuracy: 0.9507 - loss: 0.1855
Epoch 88/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - binary_accuracy: 0.9484 - loss: 0.1378
Epoch 89/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - binary_accuracy: 0.9296 - loss: 0.3518
Epoch 90/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - binary_accuracy: 0.9413 - loss: 0.2016
Epoch 91/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - binary_accuracy: 0.9484 - loss: 0.1908
Epoch 92/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - binary_accuracy: 0.9272 - loss: 0.2724
Epoch 93/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - binary_accuracy: 0.9038 - loss: 0.4868
Epoch 94/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - binary_accuracy: 0.9155 - loss: 0.4212
Epoch 95/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - binary_accuracy: 0.9225 - loss: 0.3186
Epoch 96/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - binary_accuracy: 0.9296 - loss: 0.3574
Epoch 97/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - binary_accuracy: 0.9460 - loss: 0.1865
Epoch 98/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - binary_accuracy: 0.9507 - loss: 0.1904
Epoch 99/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - binary_accuracy: 0.9319 - loss: 0.3807
Epoch 100/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - binary_accuracy: 0.9413 - loss: 0.2297

In [17]:
previsoes = rede_neural.predict(X_test) #fazendo as previsoes

5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 47ms/step

In [19]:
previsoes = previsoes > 0.5 #pegando so as acima de 0.5

In [20]:
previsoes #a linha anterior jogou os valores pra true ou false pra comparar com o valor real do Y q esta embaixo

array([[ True],
       [False],
       [False],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [False],
       [ True],
       [False],
       [ True],
       [ True],
       [ True],
       [False],
       [ True],
       [ True],
       [False],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [False],
       [False],
       [False],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [False],
       [False],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [False],
       [ True],
       [False],
       [False],
       [ True],
       [False],
       [ True],
       [ True],
       [ True],
       [ True],
       [False],
       [ True],
       [ True],
       [False],
       [False],
       [False],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [False],
       [ True],
       [False],
       [ True],
       [ True],
       [ True],
       [ True],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [ True],
       [ True],
       [ True],
       [False],
       [ True],
       [ True],
       [False],
       [False],
       [ True],
       [False],
       [ True],
       [ True],
       [False],
       [ True],
       [ True],
       [False],
       [False],
       [ True],
       [False],
       [ True],
       [ True],
       [ True],
       [ True],
       [False],
       [ True],
       [False],
       [ True],
       [False],
       [False],
       [ True],
       [False],
       [ True],
       [ True],
       [False],
       [ True],
       [ True],
       [ True],
       [False],
       [ True],
       [ True],
       [False],
       [ True],
       [ True],
       [ True],
       [ True],
       [False],
       [ True],
       [False],
       [ True],
       [False],
       [False],
       [ True],
       [ True],
       [ True],
       [False],
       [ True],
       [ True],
       [ True],
       [False],
       [False],
       [ True],
       [ True],
       [False],
       [False],
       [False],
       [False]])

In [21]:
Y_test #Y real pra comparar com o X

     0
268  1
352  0
237  0
515  1
306  1
..  ..
188  1
259  0
366  0
302  0
157  1

[143 rows x 1 columns]

In [23]:
from sklearn.metrics import accuracy_score, confusion_matrix #imports

In [25]:
accuracy_score(Y_test, previsoes) #vendo a acuracia

0.9090909090909091

In [26]:
confusion_matrix(Y_test, previsoes) #jogando pra matriz de confusao

array([[49, 10],
       [ 3, 81]])

In [27]:
49 + 81, 3 + 10

(130, 13)

In [28]:
130 / 143, 13 / 143 #somas e divisoes pra mostrar como foi calculado os valores anteriores

(0.9090909090909091, 0.09090909090909091)

In [29]:
rede_neural.evaluate(X_test, Y_test) #vendo quanto ela pontuou comparando os valores

5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 53ms/step - binary_accuracy: 0.9091 - loss: 0.4055

[0.4054584503173828, 0.9090909361839294]

# Adicionando mais camadas

In [30]:
rede_neural = Sequential([
    tf.keras.layers.InputLayer(shape = (30,)),
    tf.keras.layers.Dense(units = 16, activation = 'relu', kernel_initializer = 'random_uniform'),
    tf.keras.layers.Dense(units = 16, activation = 'relu', kernel_initializer = 'random_uniform'),
    tf.keras.layers.Dense(units = 1, activation = 'sigmoid')
]) #criando mais uma camada oculta

In [31]:
rede_neural.summary() #msm coisa denovo, vendo como ela foi criada

Model: "sequential_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense_2 (Dense)                 │ (None, 16)             │           496 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_3 (Dense)                 │ (None, 16)             │           272 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_4 (Dense)                 │ (None, 1)              │            17 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 785 (3.07 KB)

 Trainable params: 785 (3.07 KB)

 Non-trainable params: 0 (0.00 B)

In [32]:
otimizador = tf.keras.optimizers.Adam(learning_rate = 0.001, clipvalue = 0.5) #defiinindo um otimizador

In [33]:
rede_neural.compile(optimizer = otimizador, loss = 'binary_crossentropy', metrics = ['binary_accuracy']) #compilando ela usando o otimizador anterior

In [35]:
rede_neural.fit(X_train, Y_train, batch_size = 10, epochs = 100) #treinando

Epoch 1/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - binary_accuracy: 0.8545 - loss: 0.5213
Epoch 2/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - binary_accuracy: 0.8404 - loss: 0.6184
Epoch 3/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - binary_accuracy: 0.8638 - loss: 0.5562
Epoch 4/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - binary_accuracy: 0.8216 - loss: 0.6557
Epoch 5/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - binary_accuracy: 0.8474 - loss: 0.5481
Epoch 6/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - binary_accuracy: 0.8357 - loss: 0.5561
Epoch 7/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - binary_accuracy: 0.8239 - loss: 0.5980
Epoch 8/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - binary_accuracy: 0.8380 - loss: 0.5061
Epoch 9/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - binary_accuracy: 0.8756 - loss: 0.5151
Epoch 10/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - binary_accuracy: 0.8380 - loss: 0.5735
Epoch 11/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - binary_accuracy: 0.8380 - loss: 0.6426
Epoch 12/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - binary_accuracy: 0.8192 - loss: 0.6949
Epoch 13/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - binary_accuracy: 0.8451 - loss: 0.5128
Epoch 14/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - binary_accuracy: 0.8333 - loss: 0.4877
Epoch 15/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - binary_accuracy: 0.8427 - loss: 0.4601
Epoch 16/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - binary_accuracy: 0.8662 - loss: 0.4470
Epoch 17/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - binary_accuracy: 0.8638 - loss: 0.4830
Epoch 18/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - binary_accuracy: 0.8826 - loss: 0.4200
Epoch 19/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - binary_accuracy: 0.8685 - loss: 0.4761
Epoch 20/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - binary_accuracy: 0.8404 - loss: 0.5650
Epoch 21/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - binary_accuracy: 0.8592 - loss: 0.5461
Epoch 22/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - binary_accuracy: 0.8404 - loss: 0.7104
Epoch 23/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - binary_accuracy: 0.8310 - loss: 1.1510
Epoch 24/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - binary_accuracy: 0.8521 - loss: 0.6382
Epoch 25/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - binary_accuracy: 0.8709 - loss: 0.5630
Epoch 26/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - binary_accuracy: 0.8380 - loss: 0.7349
Epoch 27/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - binary_accuracy: 0.8615 - loss: 0.6760
Epoch 28/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 991us/step - binary_accuracy: 0.8756 - loss: 0.5809
Epoch 29/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - binary_accuracy: 0.8404 - loss: 0.5828
Epoch 30/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - binary_accuracy: 0.8380 - loss: 0.6480
Epoch 31/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - binary_accuracy: 0.8592 - loss: 0.5693
Epoch 32/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - binary_accuracy: 0.8592 - loss: 0.5447
Epoch 33/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - binary_accuracy: 0.8545 - loss: 0.5977
Epoch 34/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - binary_accuracy: 0.8615 - loss: 0.6077
Epoch 35/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - binary_accuracy: 0.8451 - loss: 0.6117
Epoch 36/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - binary_accuracy: 0.8427 - loss: 0.5695
Epoch 37/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - binary_accuracy: 0.8803 - loss: 0.4518
Epoch 38/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - binary_accuracy: 0.8756 - loss: 0.4961
Epoch 39/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - binary_accuracy: 0.8357 - loss: 0.6039
Epoch 40/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - binary_accuracy: 0.8638 - loss: 0.4732
Epoch 41/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 988us/step - binary_accuracy: 0.8756 - loss: 0.5224
Epoch 42/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - binary_accuracy: 0.8427 - loss: 0.6658
Epoch 43/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - binary_accuracy: 0.8239 - loss: 1.0572
Epoch 44/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - binary_accuracy: 0.8615 - loss: 0.5638
Epoch 45/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - binary_accuracy: 0.8568 - loss: 0.6166
Epoch 46/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - binary_accuracy: 0.8521 - loss: 0.7025
Epoch 47/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - binary_accuracy: 0.8685 - loss: 0.7863
Epoch 48/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - binary_accuracy: 0.8451 - loss: 0.8433
Epoch 49/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - binary_accuracy: 0.8709 - loss: 0.5561
Epoch 50/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - binary_accuracy: 0.8521 - loss: 0.6663
Epoch 51/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - binary_accuracy: 0.8333 - loss: 0.6382
Epoch 52/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - binary_accuracy: 0.8592 - loss: 0.6649
Epoch 53/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - binary_accuracy: 0.8568 - loss: 0.6991
Epoch 54/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - binary_accuracy: 0.8404 - loss: 0.8705
Epoch 55/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 999us/step - binary_accuracy: 0.8592 - loss: 0.8120
Epoch 56/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - binary_accuracy: 0.8638 - loss: 0.5716
Epoch 57/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - binary_accuracy: 0.8779 - loss: 0.6264
Epoch 58/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - binary_accuracy: 0.8779 - loss: 0.8414
Epoch 59/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - binary_accuracy: 0.8592 - loss: 0.6427
Epoch 60/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - binary_accuracy: 0.8756 - loss: 0.6490
Epoch 61/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - binary_accuracy: 0.8615 - loss: 0.7426
Epoch 62/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - binary_accuracy: 0.8568 - loss: 0.6976
Epoch 63/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - binary_accuracy: 0.8075 - loss: 0.9045
Epoch 64/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - binary_accuracy: 0.8404 - loss: 0.8793
Epoch 65/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - binary_accuracy: 0.8521 - loss: 0.7873
Epoch 66/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - binary_accuracy: 0.8404 - loss: 0.8998
Epoch 67/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - binary_accuracy: 0.8545 - loss: 0.8019
Epoch 68/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - binary_accuracy: 0.8498 - loss: 0.8433
Epoch 69/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - binary_accuracy: 0.8451 - loss: 0.9509
Epoch 70/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - binary_accuracy: 0.8592 - loss: 0.9257
Epoch 71/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - binary_accuracy: 0.8662 - loss: 0.9262
Epoch 72/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - binary_accuracy: 0.8709 - loss: 0.7641
Epoch 73/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - binary_accuracy: 0.8333 - loss: 0.9918
Epoch 74/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - binary_accuracy: 0.8685 - loss: 0.8093
Epoch 75/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - binary_accuracy: 0.8615 - loss: 0.8924
Epoch 76/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - binary_accuracy: 0.8685 - loss: 0.9702
Epoch 77/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - binary_accuracy: 0.8474 - loss: 0.9573
Epoch 78/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - binary_accuracy: 0.8333 - loss: 1.1781
Epoch 79/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - binary_accuracy: 0.8474 - loss: 1.0238
Epoch 80/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - binary_accuracy: 0.8545 - loss: 0.8137
Epoch 81/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - binary_accuracy: 0.8545 - loss: 1.0161
Epoch 82/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - binary_accuracy: 0.8451 - loss: 0.9372
Epoch 83/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - binary_accuracy: 0.8662 - loss: 0.9877
Epoch 84/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - binary_accuracy: 0.8685 - loss: 0.8719
Epoch 85/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - binary_accuracy: 0.8521 - loss: 1.0380
Epoch 86/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - binary_accuracy: 0.8310 - loss: 1.0987
Epoch 87/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - binary_accuracy: 0.8404 - loss: 0.9525
Epoch 88/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - binary_accuracy: 0.8427 - loss: 1.1540
Epoch 89/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - binary_accuracy: 0.8615 - loss: 1.0701
Epoch 90/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - binary_accuracy: 0.8615 - loss: 0.9375
Epoch 91/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - binary_accuracy: 0.8615 - loss: 0.9089
Epoch 92/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - binary_accuracy: 0.8286 - loss: 1.6914
Epoch 93/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - binary_accuracy: 0.8498 - loss: 1.5623
Epoch 94/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - binary_accuracy: 0.8498 - loss: 1.0820
Epoch 95/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 986us/step - binary_accuracy: 0.8169 - loss: 1.7037
Epoch 96/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - binary_accuracy: 0.8357 - loss: 1.4572
Epoch 97/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - binary_accuracy: 0.8028 - loss: 1.5505
Epoch 98/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - binary_accuracy: 0.8310 - loss: 1.3316
Epoch 99/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - binary_accuracy: 0.8380 - loss: 1.2826
Epoch 100/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - binary_accuracy: 0.7934 - loss: 1.5361

In [36]:
rede_neural.evaluate(X_test, Y_test) #pontuacao

5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 50ms/step - binary_accuracy: 0.7273 - loss: 2.8889

[2.888857364654541, 0.7272727489471436]

In [39]:
pesos0 = rede_neural.layers[0].get_weights() #vendo os pesos
pesos0

[array([[ 2.65183300e-01,  4.34310548e-02, -6.68541074e-01,
         -1.79246306e-01,  3.80128682e-01,  1.00262478e-01,
         -3.78358662e-02, -5.52572720e-02,  2.84750640e-01,
         -1.69818878e-01,  4.31555927e-01, -1.46236448e-02,
         -5.72967529e-01,  1.18278220e-01,  4.34828550e-01,
         -5.14235020e-01],
        [ 3.06860656e-01,  1.67038828e-01, -3.82459551e-01,
         -2.53416508e-01,  2.20276311e-01, -7.54185161e-03,
         -8.47308934e-02,  3.79734254e-03,  3.37823004e-01,
          9.88873243e-02,  1.23829320e-01, -8.15397501e-02,
         -3.28272372e-01,  1.88101292e-01,  3.81596208e-01,
         -3.86350244e-01],
        [ 1.25536323e-01,  9.85483527e-02, -1.42386973e-01,
         -4.27784435e-02,  2.82607879e-02, -1.17663490e-02,
         -3.03927101e-02,  3.11048143e-02,  7.58134127e-02,
         -1.10116433e-02,  2.66725063e-01, -4.73685935e-02,
         -2.13929281e-01, -2.41854740e-03,  9.97563750e-02,
          9.61201414e-02],
        [-5.18807508e-02, -1.13661690e-02,  1.44737065e-01,
          8.71069431e-02, -1.37654945e-01,  9.97166848e-04,
          1.75214820e-02, -5.50691597e-02, -6.01082891e-02,
          1.07597679e-01,  2.03741610e-01,  4.67110686e-02,
          2.60867178e-01,  5.29289618e-02, -1.09859526e-01,
          1.60775349e-01],
        [-1.74048722e-01,  1.08473701e-02, -4.27307308e-01,
         -8.34904704e-03,  1.69132575e-02, -6.35885298e-02,
         -1.18232913e-01,  3.98894809e-02, -1.06712282e-01,
         -4.69032258e-01,  1.02500483e-01,  2.14312859e-02,
         -1.07856922e-01,  1.89403892e-02, -3.77437711e-01,
          8.88348594e-02],
        [ 2.21751764e-01, -4.74803299e-02, -2.93936193e-01,
         -1.03675187e-01,  2.26706430e-01,  4.43456732e-02,
         -5.30125499e-02,  4.33118157e-02,  8.16041529e-02,
         -2.01575205e-01,  2.34461993e-01,  1.30983785e-01,
         -4.76726085e-01, -1.16640404e-01,  1.84082955e-01,
          2.58327067e-01],
        [-1.06687360e-01, -3.96216586e-02, -2.08272472e-01,
         -1.99779674e-01, -2.97004670e-01, -5.48446514e-02,
          5.83454929e-02,  2.78773252e-02,  1.96018323e-01,
         -1.27930418e-01, -2.00746879e-02,  5.03457844e-01,
         -5.54184541e-02,  1.46784022e-01, -2.75433868e-01,
          8.76067728e-02],
        [-5.72418645e-02, -3.92154045e-02, -3.40886623e-01,
         -1.95861846e-01,  8.98478404e-02, -2.09785327e-02,
          1.45514458e-01,  3.28781679e-02, -3.29642445e-01,
         -3.38856846e-01,  2.50613958e-01,  3.12937289e-01,
         -4.03042704e-01, -2.13548109e-01, -2.26129726e-01,
          2.03786328e-01],
        [-4.98494208e-02,  2.63552293e-02, -1.31493539e-01,
          2.15726322e-03, -1.06318466e-01,  1.45102134e-02,
          2.27731258e-01, -3.58330198e-02,  1.33762047e-01,
         -3.75851303e-01, -2.68792659e-01, -4.37150627e-01,
          5.06977849e-02,  5.16248457e-02,  1.00782153e-03,
          4.20519531e-01],
        [ 1.75260492e-02,  1.08779959e-01,  5.47076643e-01,
          2.54179209e-01,  3.49992126e-01,  8.50368366e-02,
         -1.10789523e-01, -4.66019064e-02,  1.86895952e-01,
          2.77029544e-01,  7.20437020e-02, -4.76844341e-01,
          3.39723408e-01,  5.60314834e-01, -1.10169619e-01,
         -1.35621220e-01],
        [-5.48998266e-02, -1.55140117e-01, -1.60751969e-01,
         -6.65192977e-02, -1.56730972e-02, -1.08966499e-03,
          1.60546184e-01, -1.29304063e-02, -7.11342320e-02,
         -1.17694326e-01,  5.35538904e-02,  5.17430156e-02,
          1.58387080e-01,  5.59490584e-02,  3.90523635e-02,
          2.68916469e-02],
        [ 3.57787199e-02, -4.34420537e-03, -5.93282342e-01,
         -1.44404918e-01, -3.48560140e-02, -5.20160012e-02,
         -3.01321238e-01,  1.42568415e-02,  1.69721376e-02,
         -5.15945971e-01,  8.88865739e-02, -1.37460753e-01,
         -2.73885041e-01, -2.68641580e-02, -4.33336422e-02,
          4.75034863e-01],
        [-2.83553023e-02,  4.62470157e-03,  2.78749883e-01,
          1.78231653e-02, -1.14621222e-02,  5.10002207e-03,
         -1.20796129e-01, -2.59817690e-02,  2.58721355e-02,
          3.36345918e-02,  1.10364214e-01, -6.92491978e-02,
         -4.34589028e-01, -6.66840300e-02,  1.45052187e-03,
          4.03468423e-02],
        [ 5.17525196e-01, -2.50240564e-01, -2.31331658e+00,
         -1.33692217e+00,  9.02669787e-01, -1.52019337e-01,
          6.38055980e-01,  1.35101716e-03,  4.48498636e-01,
         -1.45065919e-01,  1.37902761e+00,  1.63454556e+00,
         -5.74053049e-01,  3.49764794e-01,  1.38608158e+00,
         -1.84673405e+00],
        [ 2.56820351e-01,  4.15719002e-02, -4.88547891e-01,
         -1.74224809e-01,  2.13968292e-01, -9.54434462e-03,
         -3.25567931e-01,  4.42388607e-03,  2.92400658e-01,
          3.98997843e-01,  2.35759184e-01, -1.75664634e-01,
         -3.09535533e-01, -4.40013362e-04,  5.02452016e-01,
         -4.60098743e-01],
        [ 2.42767349e-01, -1.51896909e-01, -5.60121298e-01,
         -3.19939494e-01, -2.80817509e-01, -2.43814103e-02,
          1.65066853e-01, -4.05322239e-02,  2.71496445e-01,
         -6.61733449e-02,  2.82845318e-01,  3.15951288e-01,
         -6.33385718e-01, -2.56831676e-01,  3.14209253e-01,
         -3.10580730e-01],
        [-6.39930069e-02, -2.89546214e-02, -3.89364250e-02,
         -9.50405449e-02,  1.63449258e-01, -8.61935988e-02,
         -7.57043809e-02, -4.84338962e-02,  2.10707620e-01,
         -3.46914493e-02,  1.05848074e-01, -8.01240653e-03,
         -1.61065102e-01,  8.45268890e-02, -1.03550253e-03,
          1.41251162e-01],
        [ 1.41772643e-01, -1.50716491e-03, -3.44952315e-01,
         -5.97289093e-02, -5.15316486e-01,  1.33053702e-03,
         -3.54594648e-01,  2.47329082e-02,  3.83888371e-02,
         -4.90766943e-01, -2.25740239e-01, -4.31995451e-01,
          1.00655389e+00,  3.23876649e-01,  5.04873581e-02,
          2.48334646e-01],
        [-6.38272017e-02,  1.85052514e-01,  4.67329055e-01,
          2.47862726e-01, -2.55826712e-02,  4.86324541e-02,
         -5.52110493e-01, -1.24578811e-02,  8.60049576e-03,
          5.55442035e-01, -1.97652891e-01, -1.86614275e-01,
          2.74292260e-01,  9.44332331e-02, -7.17947558e-02,
          1.17266253e-01],
        [ 4.04349625e-01,  9.96038020e-02, -9.94857669e-01,
         -6.08919442e-01,  9.24517155e-01, -3.07459366e-02,
          4.47126180e-02,  7.17629911e-03,  3.06343049e-01,
          3.52449119e-01,  5.99468231e-01,  4.21602041e-01,
         -6.04147539e-02,  2.95723259e-01,  8.61471176e-01,
         -1.22018909e+00],
        [ 2.81542212e-01, -3.77613157e-02, -8.93553197e-01,
         -4.05019194e-01,  5.18321395e-01, -1.43064987e-02,
          5.81814051e-02, -2.61050183e-02,  3.01703095e-01,
         -1.81999460e-01,  4.94183123e-01,  1.51393041e-01,
         -5.77853620e-01,  4.89391387e-02,  5.21278679e-01,
         -6.24469399e-01],
        [ 3.43882173e-01,  1.20140254e-01, -4.04793143e-01,
         -3.13532501e-01,  2.40021884e-01, -6.27552858e-03,
         -4.59834002e-03, -3.41225564e-02,  2.96183884e-01,
          9.26725641e-02,  1.68955654e-01, -7.85523932e-03,
         -4.15821105e-01,  9.81367975e-02,  3.60643774e-01,
         -5.17447352e-01],
        [ 4.33915108e-02,  7.48180225e-03, -2.93032318e-01,
         -1.38921678e-01,  1.30337611e-01, -4.94182110e-03,
          6.31677806e-02,  3.12892124e-02,  4.94849123e-02,
         -2.97859851e-02,  3.39307874e-01,  7.44342506e-02,
         -2.20899120e-01,  2.99075805e-02,  1.02304749e-01,
         -4.97561283e-02],
        [-5.22271134e-02, -3.87820788e-02,  5.32706790e-02,
         -5.75905181e-02,  1.72189660e-02, -3.09092551e-02,
          5.32982722e-02, -4.93887104e-02, -5.36275357e-02,
          1.27211869e-01,  1.97824717e-01,  2.16259152e-01,
          3.19444954e-01,  4.23131511e-02, -2.44524963e-02,
         -3.14991735e-02],
        [ 2.22138092e-01, -2.45108038e-01,  8.36504102e-02,
         -2.39177309e-02,  1.73033476e-02, -4.69627557e-03,
          1.88331887e-01, -3.55173796e-02,  3.02913159e-01,
         -4.58058417e-02, -9.53729078e-02,  7.65669718e-02,
         -5.15575940e-03, -7.19384477e-02,  1.66134313e-01,
          1.77005738e-01],
        [ 1.96772873e-01, -8.60725939e-02, -5.88539094e-02,
         -1.67197391e-01, -8.14139843e-02, -3.88310221e-03,
          3.03114802e-01, -9.33657924e-04, -1.96749359e-01,
         -2.25232542e-01,  2.34176978e-01, -2.48954985e-02,
          2.55464584e-01, -1.05689220e-01,  1.78941768e-02,
          4.65896815e-01],
        [-5.28371185e-02, -5.27516901e-02,  2.12078895e-02,
         -1.35796845e-01, -2.33553723e-01, -1.78241227e-02,
          4.44275022e-01,  3.37775238e-02, -4.12989706e-02,
         -3.11663002e-01,  3.25124115e-02, -4.19339687e-02,
          3.50176901e-01,  8.48303810e-02, -1.04727916e-01,
          3.39475244e-01],
        [ 4.37437147e-02, -7.72685409e-02, -8.20676863e-01,
         -6.08577192e-01, -2.93073151e-02, -1.25497833e-01,
          3.29668909e-01,  6.42765500e-03,  2.53664870e-02,
         -3.54357690e-01,  2.81373233e-01,  3.76976460e-01,
         -2.37689763e-01,  1.73956677e-01,  2.07982242e-01,
         -2.52134293e-01],
        [ 9.11978483e-02, -2.01484740e-01,  2.98593700e-01,
         -5.97633906e-02, -1.08645216e-01, -3.06634381e-02,
          8.69141668e-02, -1.71494146e-03,  2.54460365e-01,
         -2.90019414e-03, -8.07048455e-02,  1.53838515e-01,
         -1.82811067e-01, -8.89323130e-02,  2.43287161e-01,
          2.03630075e-01],
        [-1.45406881e-03,  8.99970308e-02, -6.85817957e-01,
         -4.65402335e-01,  4.13198829e-01, -1.37724793e-02,
          4.03883189e-01, -4.98676784e-02,  1.33137479e-01,
          1.92720488e-01, -2.41791103e-02,  5.76920033e-01,
          2.93538272e-02,  1.39970779e-01,  5.82281649e-01,
         -9.51846719e-01]], dtype=float32),
 array([ 0.19282658,  0.24833344,  0.28429148,  0.27775633, -0.15824264,
        -0.01225468, -0.5763026 , -0.00667974,  0.32779932, -0.03063077,
        -0.14977612, -0.78346455, -0.36326063,  0.12506166, -0.24859074,
         0.4410714 ], dtype=float32)]

In [40]:
len(pesos0) #tamanho dos pesos

2

In [41]:
len(pesos0[1]) #tamanhio dos pesos0 na posicao 1

16

In [42]:
pesos0[0] #pesos 0 posicao 0

array([[ 2.65183300e-01,  4.34310548e-02, -6.68541074e-01,
        -1.79246306e-01,  3.80128682e-01,  1.00262478e-01,
        -3.78358662e-02, -5.52572720e-02,  2.84750640e-01,
        -1.69818878e-01,  4.31555927e-01, -1.46236448e-02,
        -5.72967529e-01,  1.18278220e-01,  4.34828550e-01,
        -5.14235020e-01],
       [ 3.06860656e-01,  1.67038828e-01, -3.82459551e-01,
        -2.53416508e-01,  2.20276311e-01, -7.54185161e-03,
        -8.47308934e-02,  3.79734254e-03,  3.37823004e-01,
         9.88873243e-02,  1.23829320e-01, -8.15397501e-02,
        -3.28272372e-01,  1.88101292e-01,  3.81596208e-01,
        -3.86350244e-01],
       [ 1.25536323e-01,  9.85483527e-02, -1.42386973e-01,
        -4.27784435e-02,  2.82607879e-02, -1.17663490e-02,
        -3.03927101e-02,  3.11048143e-02,  7.58134127e-02,
        -1.10116433e-02,  2.66725063e-01, -4.73685935e-02,
        -2.13929281e-01, -2.41854740e-03,  9.97563750e-02,
         9.61201414e-02],
       [-5.18807508e-02, -1.13661690e-02,  1.44737065e-01,
         8.71069431e-02, -1.37654945e-01,  9.97166848e-04,
         1.75214820e-02, -5.50691597e-02, -6.01082891e-02,
         1.07597679e-01,  2.03741610e-01,  4.67110686e-02,
         2.60867178e-01,  5.29289618e-02, -1.09859526e-01,
         1.60775349e-01],
       [-1.74048722e-01,  1.08473701e-02, -4.27307308e-01,
        -8.34904704e-03,  1.69132575e-02, -6.35885298e-02,
        -1.18232913e-01,  3.98894809e-02, -1.06712282e-01,
        -4.69032258e-01,  1.02500483e-01,  2.14312859e-02,
        -1.07856922e-01,  1.89403892e-02, -3.77437711e-01,
         8.88348594e-02],
       [ 2.21751764e-01, -4.74803299e-02, -2.93936193e-01,
        -1.03675187e-01,  2.26706430e-01,  4.43456732e-02,
        -5.30125499e-02,  4.33118157e-02,  8.16041529e-02,
        -2.01575205e-01,  2.34461993e-01,  1.30983785e-01,
        -4.76726085e-01, -1.16640404e-01,  1.84082955e-01,
         2.58327067e-01],
       [-1.06687360e-01, -3.96216586e-02, -2.08272472e-01,
        -1.99779674e-01, -2.97004670e-01, -5.48446514e-02,
         5.83454929e-02,  2.78773252e-02,  1.96018323e-01,
        -1.27930418e-01, -2.00746879e-02,  5.03457844e-01,
        -5.54184541e-02,  1.46784022e-01, -2.75433868e-01,
         8.76067728e-02],
       [-5.72418645e-02, -3.92154045e-02, -3.40886623e-01,
        -1.95861846e-01,  8.98478404e-02, -2.09785327e-02,
         1.45514458e-01,  3.28781679e-02, -3.29642445e-01,
        -3.38856846e-01,  2.50613958e-01,  3.12937289e-01,
        -4.03042704e-01, -2.13548109e-01, -2.26129726e-01,
         2.03786328e-01],
       [-4.98494208e-02,  2.63552293e-02, -1.31493539e-01,
         2.15726322e-03, -1.06318466e-01,  1.45102134e-02,
         2.27731258e-01, -3.58330198e-02,  1.33762047e-01,
        -3.75851303e-01, -2.68792659e-01, -4.37150627e-01,
         5.06977849e-02,  5.16248457e-02,  1.00782153e-03,
         4.20519531e-01],
       [ 1.75260492e-02,  1.08779959e-01,  5.47076643e-01,
         2.54179209e-01,  3.49992126e-01,  8.50368366e-02,
        -1.10789523e-01, -4.66019064e-02,  1.86895952e-01,
         2.77029544e-01,  7.20437020e-02, -4.76844341e-01,
         3.39723408e-01,  5.60314834e-01, -1.10169619e-01,
        -1.35621220e-01],
       [-5.48998266e-02, -1.55140117e-01, -1.60751969e-01,
        -6.65192977e-02, -1.56730972e-02, -1.08966499e-03,
         1.60546184e-01, -1.29304063e-02, -7.11342320e-02,
        -1.17694326e-01,  5.35538904e-02,  5.17430156e-02,
         1.58387080e-01,  5.59490584e-02,  3.90523635e-02,
         2.68916469e-02],
       [ 3.57787199e-02, -4.34420537e-03, -5.93282342e-01,
        -1.44404918e-01, -3.48560140e-02, -5.20160012e-02,
        -3.01321238e-01,  1.42568415e-02,  1.69721376e-02,
        -5.15945971e-01,  8.88865739e-02, -1.37460753e-01,
        -2.73885041e-01, -2.68641580e-02, -4.33336422e-02,
         4.75034863e-01],
       [-2.83553023e-02,  4.62470157e-03,  2.78749883e-01,
         1.78231653e-02, -1.14621222e-02,  5.10002207e-03,
        -1.20796129e-01, -2.59817690e-02,  2.58721355e-02,
         3.36345918e-02,  1.10364214e-01, -6.92491978e-02,
        -4.34589028e-01, -6.66840300e-02,  1.45052187e-03,
         4.03468423e-02],
       [ 5.17525196e-01, -2.50240564e-01, -2.31331658e+00,
        -1.33692217e+00,  9.02669787e-01, -1.52019337e-01,
         6.38055980e-01,  1.35101716e-03,  4.48498636e-01,
        -1.45065919e-01,  1.37902761e+00,  1.63454556e+00,
        -5.74053049e-01,  3.49764794e-01,  1.38608158e+00,
        -1.84673405e+00],
       [ 2.56820351e-01,  4.15719002e-02, -4.88547891e-01,
        -1.74224809e-01,  2.13968292e-01, -9.54434462e-03,
        -3.25567931e-01,  4.42388607e-03,  2.92400658e-01,
         3.98997843e-01,  2.35759184e-01, -1.75664634e-01,
        -3.09535533e-01, -4.40013362e-04,  5.02452016e-01,
        -4.60098743e-01],
       [ 2.42767349e-01, -1.51896909e-01, -5.60121298e-01,
        -3.19939494e-01, -2.80817509e-01, -2.43814103e-02,
         1.65066853e-01, -4.05322239e-02,  2.71496445e-01,
        -6.61733449e-02,  2.82845318e-01,  3.15951288e-01,
        -6.33385718e-01, -2.56831676e-01,  3.14209253e-01,
        -3.10580730e-01],
       [-6.39930069e-02, -2.89546214e-02, -3.89364250e-02,
        -9.50405449e-02,  1.63449258e-01, -8.61935988e-02,
        -7.57043809e-02, -4.84338962e-02,  2.10707620e-01,
        -3.46914493e-02,  1.05848074e-01, -8.01240653e-03,
        -1.61065102e-01,  8.45268890e-02, -1.03550253e-03,
         1.41251162e-01],
       [ 1.41772643e-01, -1.50716491e-03, -3.44952315e-01,
        -5.97289093e-02, -5.15316486e-01,  1.33053702e-03,
        -3.54594648e-01,  2.47329082e-02,  3.83888371e-02,
        -4.90766943e-01, -2.25740239e-01, -4.31995451e-01,
         1.00655389e+00,  3.23876649e-01,  5.04873581e-02,
         2.48334646e-01],
       [-6.38272017e-02,  1.85052514e-01,  4.67329055e-01,
         2.47862726e-01, -2.55826712e-02,  4.86324541e-02,
        -5.52110493e-01, -1.24578811e-02,  8.60049576e-03,
         5.55442035e-01, -1.97652891e-01, -1.86614275e-01,
         2.74292260e-01,  9.44332331e-02, -7.17947558e-02,
         1.17266253e-01],
       [ 4.04349625e-01,  9.96038020e-02, -9.94857669e-01,
        -6.08919442e-01,  9.24517155e-01, -3.07459366e-02,
         4.47126180e-02,  7.17629911e-03,  3.06343049e-01,
         3.52449119e-01,  5.99468231e-01,  4.21602041e-01,
        -6.04147539e-02,  2.95723259e-01,  8.61471176e-01,
        -1.22018909e+00],
       [ 2.81542212e-01, -3.77613157e-02, -8.93553197e-01,
        -4.05019194e-01,  5.18321395e-01, -1.43064987e-02,
         5.81814051e-02, -2.61050183e-02,  3.01703095e-01,
        -1.81999460e-01,  4.94183123e-01,  1.51393041e-01,
        -5.77853620e-01,  4.89391387e-02,  5.21278679e-01,
        -6.24469399e-01],
       [ 3.43882173e-01,  1.20140254e-01, -4.04793143e-01,
        -3.13532501e-01,  2.40021884e-01, -6.27552858e-03,
        -4.59834002e-03, -3.41225564e-02,  2.96183884e-01,
         9.26725641e-02,  1.68955654e-01, -7.85523932e-03,
        -4.15821105e-01,  9.81367975e-02,  3.60643774e-01,
        -5.17447352e-01],
       [ 4.33915108e-02,  7.48180225e-03, -2.93032318e-01,
        -1.38921678e-01,  1.30337611e-01, -4.94182110e-03,
         6.31677806e-02,  3.12892124e-02,  4.94849123e-02,
        -2.97859851e-02,  3.39307874e-01,  7.44342506e-02,
        -2.20899120e-01,  2.99075805e-02,  1.02304749e-01,
        -4.97561283e-02],
       [-5.22271134e-02, -3.87820788e-02,  5.32706790e-02,
        -5.75905181e-02,  1.72189660e-02, -3.09092551e-02,
         5.32982722e-02, -4.93887104e-02, -5.36275357e-02,
         1.27211869e-01,  1.97824717e-01,  2.16259152e-01,
         3.19444954e-01,  4.23131511e-02, -2.44524963e-02,
        -3.14991735e-02],
       [ 2.22138092e-01, -2.45108038e-01,  8.36504102e-02,
        -2.39177309e-02,  1.73033476e-02, -4.69627557e-03,
         1.88331887e-01, -3.55173796e-02,  3.02913159e-01,
        -4.58058417e-02, -9.53729078e-02,  7.65669718e-02,
        -5.15575940e-03, -7.19384477e-02,  1.66134313e-01,
         1.77005738e-01],
       [ 1.96772873e-01, -8.60725939e-02, -5.88539094e-02,
        -1.67197391e-01, -8.14139843e-02, -3.88310221e-03,
         3.03114802e-01, -9.33657924e-04, -1.96749359e-01,
        -2.25232542e-01,  2.34176978e-01, -2.48954985e-02,
         2.55464584e-01, -1.05689220e-01,  1.78941768e-02,
         4.65896815e-01],
       [-5.28371185e-02, -5.27516901e-02,  2.12078895e-02,
        -1.35796845e-01, -2.33553723e-01, -1.78241227e-02,
         4.44275022e-01,  3.37775238e-02, -4.12989706e-02,
        -3.11663002e-01,  3.25124115e-02, -4.19339687e-02,
         3.50176901e-01,  8.48303810e-02, -1.04727916e-01,
         3.39475244e-01],
       [ 4.37437147e-02, -7.72685409e-02, -8.20676863e-01,
        -6.08577192e-01, -2.93073151e-02, -1.25497833e-01,
         3.29668909e-01,  6.42765500e-03,  2.53664870e-02,
        -3.54357690e-01,  2.81373233e-01,  3.76976460e-01,
        -2.37689763e-01,  1.73956677e-01,  2.07982242e-01,
        -2.52134293e-01],
       [ 9.11978483e-02, -2.01484740e-01,  2.98593700e-01,
        -5.97633906e-02, -1.08645216e-01, -3.06634381e-02,
         8.69141668e-02, -1.71494146e-03,  2.54460365e-01,
        -2.90019414e-03, -8.07048455e-02,  1.53838515e-01,
        -1.82811067e-01, -8.89323130e-02,  2.43287161e-01,
         2.03630075e-01],
       [-1.45406881e-03,  8.99970308e-02, -6.85817957e-01,
        -4.65402335e-01,  4.13198829e-01, -1.37724793e-02,
         4.03883189e-01, -4.98676784e-02,  1.33137479e-01,
         1.92720488e-01, -2.41791103e-02,  5.76920033e-01,
         2.93538272e-02,  1.39970779e-01,  5.82281649e-01,
        -9.51846719e-01]], dtype=float32)

In [43]:
len(pesos0[0]) #tamanho

30

In [45]:
pesos1 = rede_neural.layers[1].get_weights()
pesos1 #pegando os pesos na posicao 1

[array([[ 5.31063735e-01,  3.38728651e-02, -1.31294593e-01,
         -1.44690387e-02, -6.48299512e-03, -8.77666697e-02,
          5.48651338e-01,  8.44712630e-02, -6.59096017e-02,
          6.08044714e-02, -1.22114882e-01, -2.66019642e-01,
         -1.34744480e-01, -5.28127477e-02,  1.15222991e-01,
         -4.13084105e-02],
        [ 2.23467290e-01, -1.59807187e-02,  7.62550160e-02,
          3.48081104e-02, -1.15255728e-01,  1.07980043e-01,
          1.50675386e-01, -2.72850841e-02,  6.83971448e-03,
         -1.31550580e-01, -6.24094717e-02, -1.58054277e-01,
          1.59389123e-01, -5.64666763e-02,  2.43753940e-02,
          1.06180646e-01],
        [ 3.52217667e-02, -4.31690998e-02, -8.81058350e-02,
         -3.63677666e-02, -1.04400374e-01, -1.57532934e-03,
          1.84349008e-02, -1.08702652e-01, -8.92238468e-02,
         -6.97676539e-02,  2.09435672e-02,  6.53701350e-02,
          1.29115298e-01,  1.75692737e-01,  4.55517359e-02,
          2.84958243e-01],
        [-2.89647281e-01, -7.16288984e-02,  1.04286849e-01,
          6.71727443e-03, -6.63678348e-02,  4.68366705e-02,
         -1.74607767e-03, -2.01961230e-02, -2.88236681e-02,
         -6.35862499e-02, -1.20653667e-01, -1.03206344e-01,
          3.53313655e-01, -3.41238528e-02, -1.84909068e-02,
          1.31139174e-01],
        [ 2.26656929e-01,  1.43438699e-02,  3.89668137e-01,
          7.65518937e-03,  5.78239411e-02,  6.66792244e-02,
          4.03793663e-01, -6.35864362e-02,  3.24317843e-01,
         -4.86456417e-02, -5.82284749e-01, -4.25158024e-01,
          2.71142960e-01, -4.91445124e-01, -1.60197064e-01,
         -5.46336114e-01],
        [ 7.11561739e-02, -4.12415005e-02, -4.10594568e-02,
         -3.14858481e-02,  1.56962444e-04, -1.16121024e-01,
          8.80762413e-02,  3.36891972e-02, -7.02348202e-02,
          2.35532783e-02, -4.79150191e-03, -9.30688083e-02,
          4.50734943e-02,  8.19040695e-04, -2.15155352e-02,
          6.75996691e-02],
        [ 9.14570093e-02,  1.36375604e-02,  2.86683980e-02,
         -5.32926284e-02,  1.56167354e-02, -1.52438909e-01,
          9.69068930e-02,  1.27003388e-02,  5.95669029e-03,
          1.80845615e-02, -9.09141228e-02, -3.52961421e-02,
          2.65285283e-01, -3.07114273e-02,  2.52145737e-01,
          3.20343524e-02],
        [ 4.20238338e-02, -6.18088581e-02, -3.62330256e-03,
         -5.09755164e-02,  6.38133939e-03, -9.51710530e-03,
         -3.89447957e-02,  1.10893568e-03, -1.66728701e-02,
          3.86393964e-02,  1.49531681e-02,  1.93554815e-02,
          4.05274555e-02,  2.61019766e-02,  8.54267925e-03,
         -1.47053450e-02],
        [ 4.70012993e-01, -1.56908482e-01, -1.20344140e-01,
          1.86897796e-02, -2.05382943e-01,  4.72480357e-02,
          6.00489378e-01, -3.35334167e-02, -6.69100657e-02,
         -7.63684288e-02, -3.67638797e-01, -2.79812425e-01,
         -4.40041088e-02, -4.11001861e-01, -1.77198663e-01,
         -7.06150979e-02],
        [-1.46103650e-01, -1.17388116e-02,  1.68765292e-01,
         -2.26346646e-02, -5.17932475e-02, -6.50836825e-02,
         -3.36727239e-02, -7.94685166e-03, -9.20067728e-02,
         -2.28623506e-02,  1.44347459e-01,  1.32248700e-01,
          5.34272194e-02, -6.41700951e-03, -1.91331387e-01,
          1.07582979e-01],
        [-2.21179109e-02, -1.25788972e-01,  1.31405309e-01,
         -8.04733485e-02, -1.45698823e-02,  1.83953941e-02,
         -4.84549217e-02, -5.77756949e-03, -1.33228794e-01,
         -1.50792357e-02,  2.13069227e-02, -5.93175888e-02,
          6.78468049e-02, -3.74013111e-02, -6.27297387e-02,
         -1.57106102e-01],
        [ 8.23802724e-02,  6.58996776e-02,  1.28260270e-01,
         -1.51235526e-02,  5.14051653e-02, -1.03125341e-01,
          4.94226515e-02,  2.10704058e-02, -1.86945632e-01,
          7.91791603e-02,  3.73050719e-02,  1.47699758e-01,
          2.39463151e-01, -2.99930442e-02,  3.34240384e-02,
          4.06048074e-02],
        [ 7.31965378e-02, -8.24676976e-02, -1.25422433e-01,
         -2.52407100e-02, -9.79187936e-02,  1.29550487e-01,
         -4.50444147e-02, -1.94602802e-01, -5.29324859e-02,
         -1.13945000e-01, -7.09682330e-02, -1.18086465e-01,
         -1.69624910e-02,  4.33088318e-02, -1.01756394e-01,
          4.72485214e-01],
        [ 3.57234180e-01, -7.57323503e-02, -6.32635877e-02,
         -1.24518266e-02, -1.73589915e-01, -8.24996084e-02,
          3.67333174e-01, -1.22375607e-01,  2.13914916e-01,
         -1.43098757e-01, -3.70860547e-01, -2.79990226e-01,
          7.02002943e-02, -2.09011346e-01, -1.78324729e-01,
          3.43829999e-03],
        [ 2.00641245e-01, -4.58056182e-02,  2.87699997e-01,
         -5.79617545e-02,  1.11958757e-02, -2.00925469e-01,
          3.69580925e-01,  8.76724347e-03, -2.07170233e-01,
         -2.84860991e-02, -3.71515542e-01, -3.30702364e-01,
          4.72394586e-01, -3.74463588e-01,  3.17773446e-02,
         -6.97713271e-02],
        [-2.37059653e-01, -2.69406792e-02, -1.17321916e-01,
          3.51210311e-03, -8.41102377e-02, -1.74387634e-01,
         -1.09096222e-01, -3.28609385e-02,  1.13969937e-01,
         -3.65572199e-02,  3.28041092e-02,  2.27640808e-01,
          7.37496987e-02,  1.33519024e-01,  2.41876282e-02,
          1.21334523e-01]], dtype=float32),
 array([-0.00706482, -0.2177219 , -0.4886116 , -0.01879251, -0.36094335,
         0.17170443,  0.12816536, -0.16493326,  0.5035078 , -0.28722814,
         0.36209184,  0.6230984 , -0.52020043,  0.26336044,  0.33997747,
         0.18397927], dtype=float32)]

In [47]:
pesos2 = rede_neural.layers[2].get_weights() #pesos na posicao 2
pesos2

[array([[ 0.17057687],
        [-0.57522064],
        [-0.30967948],
        [-0.3791007 ],
        [-0.44659317],
        [-0.51992667],
        [ 0.23948976],
        [-0.5482887 ],
        [-0.2924064 ],
        [-0.4245076 ],
        [ 0.21390937],
        [ 0.20588812],
        [-0.15368968],
        [-0.04636224],
        [-0.68295014],
        [ 0.27224606]], dtype=float32),
 array([0.46337187], dtype=float32)]